# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23a4fb4a4c44be10c90cc91d868243001bb6485e8444dd03ecd458121a6b781f5451d4beaddb82a749277e2e0e041bed93abd741874b4a6c3a8d6efb28120027

test:
  secret_key_base: d70a7e3a022b449f839cdea815cdfcd63877319e60c96d90a2b65bd15f4d2861e4746568dc29a38878d766ca9139e87d1e76bf0d26580e8dd1f23e9bd295c31a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
